# Used with VS Code extension httpYac by Andreas Weber or REST Client by Huachao Mao

POST http://127.0.0.1:5000/user/register HTTP/1.1
content-type: application/json

{
    "username": "testuser",
    "password": "sometestingpassword",
    "email": "something@email.com"
}

POST http://127.0.0.1:5000/user/login HTTP/1.1
content-type: application/json

{
    "password": "sometestingpassword",
    "email": "something@email.com"
}

GET http://127.0.0.1:5000/protected HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMTgyODY2NywianRpIjoiYzE3Nzg2OTAtMzVhYS00Y2Q4LWFhNGItMTRlN2JiYjU5MDk1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNzMxODI4NjY3LCJjc3JmIjoiYWM1NWU3ZDAtMTQ3Ny00ZWZkLWEyNmMtYjMxYTVmNTczZDdlIiwiZXhwIjoxNzMxODI5NTY3fQ.x40UrcZ3ZFm-DCY-Qn7GVC3nOegLO2Fh9eP18M-6BjQ

{}